"""Phase 1 — identity + workspace schema, runtime role, RLS foundation.

Hand-written (NOT autogenerated) per Phase 1 Part 9. Review order:
1) runtime role → 2) tables/FKs/indexes/constraints → 3) ownership trigger →
4) RLS helper + policies → 5) runtime-role grants.

Design sources: docs/architecture/database/phase-1-data-model.md,
docs/security/rls-model.md, ADR-0013, ADR-0018, ADR-0021, ADR-0022.

Role model: the migration/admin role (``postgres`` on Supabase; superuser on
local Compose) owns the schema and performs DDL ONLY. ``studycompanion_runtime``
is a LOGIN role with NO superuser, NO BYPASSRLS, NO CREATEDB/CREATEROLE — the
only role normal application queries may use. Its password is provisioned by
``scripts/provision_runtime_role.py`` (never committed); the migration creates
the role with a NULL password so it cannot authenticate until provisioned.

RLS context: policies read ``current_setting('app.current_user_id', true)`` —
bound transaction-scoped by the application (``set_config(..., true)`` inside
the same transaction; pooling-safe, verified through the Supavisor pooler).
Missing/empty context ⇒ NULL ⇒ zero rows (fail closed).
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

revision = "0001_phase1_identity_workspace"
down_revision = None
branch_labels = None
depends_on = None

T_USERS = "users"
T_SESSIONS = "refresh_sessions"
T_SPACES = "spaces"
T_PROJECTS = "projects"
T_MEMBERSHIPS = "project_memberships"
ROLE_RUNTIME = "studycompanion_runtime"
FN_APP_USER = "app_user_id"
FN_TOUCH_UPDATED_AT = "touch_updated_at"
FN_OWNER_CONSISTENCY = "enforce_project_owner_consistency"
TG_PROJECTS_OWNER = "trg_projects_owner_consistency"
TG_SPACES_TOUCH = "trg_spaces_touch_updated_at"
TG_PROJECTS_TOUCH = "trg_projects_touch_updated_at"

# (table, policy) pairs — the single source for enable/drop symmetry.
RLS_POLICIES: list[tuple[str, str, str]] = [
    # (table, policy name, predicate column compared to app_user_id())
    (T_USERS, "users_all_access", "id"),
    (T_SESSIONS, "refresh_sessions_all_access", "user_id"),
    (T_SPACES, "spaces_all_access", "owner_id"),
    (T_PROJECTS, "projects_all_access", "owner_id"),
    (T_MEMBERSHIPS, "project_memberships_all_access", "user_id"),
]


def _provision_runtime_role(conn) -> None:  # type: ignore[no-untyped-def]
    """Idempotent role creation. NULL password: unusable until the operator
    provisioning script sets one — the migration never embeds credentials."""
    conn.execute(text(f"""
    DO $do$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{ROLE_RUNTIME}') THEN
            CREATE ROLE {ROLE_RUNTIME}
                LOGIN
                NOSUPERUSER
                NOCREATEDB
                NOCREATEROLE
                NOREPLICATION
                INHERIT
                NOBYPASSRLS;
        END IF;
    END
    $do$;
            """))
    row = conn.execute(
        text(
            "select rolsuper, rolcreaterole, rolcreatedb, rolbypassrls, rolcanlogin "
            "from pg_roles where rolname = :r"
        ),
        {"r": ROLE_RUNTIME},
    ).one()
    if bool(row.rolsuper) or bool(row.rolbypassrls) or not bool(row.rolcanlogin):
        raise RuntimeError(
            f"Runtime role {ROLE_RUNTIME} has unsafe properties: "
            f"rolsuper={row.rolsuper} rolbypassrls={row.rolbypassrls} "
            f"rolcanlogin={row.rolcanlogin} — refusing to continue"
        )


def upgrade() -> None:
    conn = op.get_bind()

    # ------------------------------------------------------------- 1) role
    _provision_runtime_role(conn)

    # ------------------------------------------------------------ 2) tables
    op.create_table(
        T_USERS,
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(16), nullable=False, server_default="learner"),
        sa.Column("status", sa.String(16), nullable=False, server_default="active"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        comment="Identity root (FR-01). RLS: owner-only via app.current_user_id.",
    )
    # Email uniqueness enforced at DATABASE level, case-insensitive (Part 3).
    op.create_index("uq_users_email_lower", T_USERS, [text("lower(email)")], unique=True)
    op.create_check_constraint("ck_users_role", T_USERS, "role IN ('learner', 'admin')")
    op.create_check_constraint("ck_users_status", T_USERS, "status IN ('active', 'disabled')")

    op.create_table(
        T_SESSIONS,
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey(
                f"{T_USERS}.id",
                ondelete="CASCADE",
                name="fk_refresh_sessions_user_id_users",
            ),
            nullable=False,
        ),
        # SHA-256 hex of the raw token — raw refresh tokens are NEVER stored.
        sa.Column("token_hash", sa.String(64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(32), nullable=True),
        sa.Column("parent_session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        comment="Rotating refresh sessions (ADR-0018). Token hashes only.",
    )
    op.create_foreign_key(
        "fk_refresh_sessions_parent_session_id_refresh_sessions",
        T_SESSIONS,
        T_SESSIONS,
        ["parent_session_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # Lookup by hash is the only supported path (Part 4).
    op.create_index("uq_refresh_sessions_token_hash", T_SESSIONS, ["token_hash"], unique=True)
    # Per-user session listing (revoke-all, audit).
    op.create_index("ix_refresh_sessions_user_id", T_SESSIONS, ["user_id"])
    # Expiration cleanup over live sessions only (partial — speculative-free).
    op.create_index(
        "ix_refresh_sessions_active_expiry",
        T_SESSIONS,
        ["expires_at"],
        postgresql_where=text("revoked_at IS NULL"),
    )
    op.create_check_constraint(
        "ck_refresh_sessions_revoked_reason",
        T_SESSIONS,
        "revoked_at IS NULL OR revoked_reason IN "
        "('rotated', 'reuse_detected', 'logout', 'admin_revoke')",
    )

    op.create_table(
        T_SPACES,
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "owner_id",
            sa.Uuid(),
            sa.ForeignKey(f"{T_USERS}.id", ondelete="CASCADE", name="fk_spaces_owner_id_users"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        comment="Top-level learner workspace (FR-05). RLS: owner-keyed.",
    )
    op.create_index(
        "uq_spaces_owner_name_lower",
        T_SPACES,
        ["owner_id", text("lower(name)")],
        unique=True,
    )

    op.create_table(
        T_PROJECTS,
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "space_id",
            sa.Uuid(),
            sa.ForeignKey(f"{T_SPACES}.id", ondelete="CASCADE", name="fk_projects_space_id_spaces"),
            nullable=False,
        ),
        # Denormalized owner: RLS predicate + owner-scoped queries without
        # joins; consistency with the owning space enforced by the trigger (3).
        sa.Column(
            "owner_id",
            sa.Uuid(),
            sa.ForeignKey(f"{T_USERS}.id", ondelete="CASCADE", name="fk_projects_owner_id_users"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("learning_goal", sa.Text(), nullable=True),
        sa.Column("status", sa.String(16), nullable=False, server_default="active"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        comment="Learning project within a space (FR-12). RLS: owner-keyed.",
    )
    op.create_index(
        "uq_projects_space_name_lower",
        T_PROJECTS,
        ["space_id", text("lower(name)")],
        unique=True,
    )
    op.create_index("ix_projects_owner_id", T_PROJECTS, ["owner_id"])
    op.create_check_constraint("ck_projects_status", T_PROJECTS, "status IN ('active', 'archived')")

    op.create_table(
        T_MEMBERSHIPS,
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "project_id",
            sa.Uuid(),
            sa.ForeignKey(
                f"{T_PROJECTS}.id",
                ondelete="CASCADE",
                name="fk_project_memberships_project_id_projects",
            ),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey(
                f"{T_USERS}.id",
                ondelete="CASCADE",
                name="fk_project_memberships_user_id_users",
            ),
            nullable=False,
        ),
        # A-16: single learner per project — only 'owner' is writable today;
        # the column is the future collaboration seam (additive relaxation).
        sa.Column("role", sa.String(16), nullable=False, server_default="owner"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        comment="Project access rows (A-16: owner-only today; collaboration deferred).",
    )
    # Exactly one owner membership per project (current supported behavior).
    op.create_index(
        "uq_project_memberships_owner_per_project",
        T_MEMBERSHIPS,
        ["project_id"],
        unique=True,
        postgresql_where=text("role = 'owner'"),
    )
    op.create_index(
        "uq_project_memberships_user_project",
        T_MEMBERSHIPS,
        ["user_id", "project_id"],
        unique=True,
    )
    op.create_check_constraint("ck_project_memberships_role", T_MEMBERSHIPS, "role IN ('owner')")

    # --------------------------------------------------- 3) trigger/functions
    conn.execute(text(f"""
    CREATE OR REPLACE FUNCTION {FN_TOUCH_UPDATED_AT}() RETURNS trigger
    LANGUAGE plpgsql SET search_path = pg_catalog AS $fn$
    BEGIN
        NEW.updated_at := now();
        RETURN NEW;
    END;
    $fn$;
            """))
    # Part 6: project.owner_id must equal its space's owner_id — plain FKs
    # cannot express this. NOTE: the SELECT inside runs under the invoking
    # role, so RLS also applies (a non-owner cannot even see the space →
    # exception → fail closed; defense in depth on top of the service layer).
    conn.execute(text(f"""
    CREATE OR REPLACE FUNCTION {FN_OWNER_CONSISTENCY}() RETURNS trigger
    LANGUAGE plpgsql SET search_path = pg_catalog, public AS $fn$
    DECLARE
        space_owner uuid;
    BEGIN
        SELECT owner_id INTO space_owner FROM {T_SPACES} WHERE id = NEW.space_id;
        IF space_owner IS NULL OR space_owner <> NEW.owner_id THEN
            RAISE EXCEPTION 'project owner must equal owning space owner'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END;
    $fn$;
            """))
    conn.execute(
        text(
            f"CREATE TRIGGER {TG_PROJECTS_OWNER} "
            f"BEFORE INSERT OR UPDATE OF space_id, owner_id ON {T_PROJECTS} "
            f"FOR EACH ROW EXECUTE FUNCTION {FN_OWNER_CONSISTENCY}()"
        )
    )
    conn.execute(
        text(
            f"CREATE TRIGGER {TG_SPACES_TOUCH} BEFORE UPDATE ON {T_SPACES} "
            f"FOR EACH ROW EXECUTE FUNCTION {FN_TOUCH_UPDATED_AT}()"
        )
    )
    conn.execute(
        text(
            f"CREATE TRIGGER {TG_PROJECTS_TOUCH} BEFORE UPDATE ON {T_PROJECTS} "
            f"FOR EACH ROW EXECUTE FUNCTION {FN_TOUCH_UPDATED_AT}()"
        )
    )

    # ------------------------------------------------- 4) RLS helper + policies
    # Invoker-rights helper reading the transaction-scoped GUC. PARANOID
    # (search_path-safe). Empty/missing context ⇒ NULL ⇒ zero rows.
    conn.execute(text(f"""
    CREATE OR REPLACE FUNCTION {FN_APP_USER}() RETURNS uuid
    LANGUAGE sql STABLE SET search_path = pg_catalog AS $fn$
        SELECT NULLIF(current_setting('app.current_user_id', true), '')::uuid;
    $fn$;
            """))

    for table, policy, column in RLS_POLICIES:
        conn.execute(text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
        conn.execute(text(f"""
    CREATE POLICY {policy} ON {table}
        AS PERMISSIVE FOR ALL TO {ROLE_RUNTIME}
        USING ({column} = {FN_APP_USER}())
        WITH CHECK ({column} = {FN_APP_USER}());
                """))

    # --------------------------------------------- 5) runtime-role privileges
    conn.execute(text(f"GRANT EXECUTE ON FUNCTION {FN_APP_USER}() TO {ROLE_RUNTIME}"))
    conn.execute(
        text(
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "
            f"{T_USERS}, {T_SESSIONS}, {T_SPACES}, {T_PROJECTS}, {T_MEMBERSHIPS} "
            f"TO {ROLE_RUNTIME}"
        )
    )
    # Future migrations' tables are automatically usable by the runtime role
    # (table-level RLS still governs every row).
    conn.execute(
        text(
            f"ALTER DEFAULT PRIVILEGES IN SCHEMA public "
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {ROLE_RUNTIME}"
        )
    )
    # alembic_version intentionally NOT granted: migration bookkeeping stays
    # privileged (runtime role can neither read nor write it).


def downgrade() -> None:
    conn = op.get_bind()

    # RLS teardown → triggers/functions → tables (FK-reverse) → default privs.
    # The runtime role is NOT dropped: dropping it would invalidate provisioned
    # credentials; role removal is an explicit operator action
    # (migration-strategy.md §downgrade).
    for table, policy, _col in RLS_POLICIES:
        conn.execute(text(f"DROP POLICY IF EXISTS {policy} ON {table}"))
        conn.execute(text(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY"))

    conn.execute(text(f"DROP TRIGGER IF EXISTS {TG_PROJECTS_TOUCH} ON {T_PROJECTS}"))
    conn.execute(text(f"DROP TRIGGER IF EXISTS {TG_SPACES_TOUCH} ON {T_SPACES}"))
    conn.execute(text(f"DROP TRIGGER IF EXISTS {TG_PROJECTS_OWNER} ON {T_PROJECTS}"))
    conn.execute(text(f"DROP FUNCTION IF EXISTS {FN_OWNER_CONSISTENCY}()"))
    conn.execute(text(f"DROP FUNCTION IF EXISTS {FN_TOUCH_UPDATED_AT}()"))
    conn.execute(text(f"DROP FUNCTION IF EXISTS {FN_APP_USER}()"))

    op.drop_table(T_MEMBERSHIPS)
    op.drop_table(T_PROJECTS)
    op.drop_table(T_SPACES)
    op.drop_table(T_SESSIONS)
    op.drop_table(T_USERS)

    conn.execute(
        text(
            f"ALTER DEFAULT PRIVILEGES IN SCHEMA public "
            f"REVOKE ALL ON TABLES FROM {ROLE_RUNTIME}"
        )
    )
